Added option to show heights (y-values) as permanent tooltips
zeldamods/objmap pull request #69
Opened 2022-01-19 13:11 UTC by savage13

Added option to show heights (y-values) as permanent tooltips

This option is in the Settings pane

To update the tooltip with the permanent flag, we needed to unbind() then re-bind() the tooltip with a different permanent flag value.

2022-01-19 13:40 UTC, leoetlino requested changes

2022-01-19 13:40 UTC, leoetlino commented on src/components/AppMap.ts
> +    m.unbindTooltip();
Can you add a comment explaining why this is necessary? (feel free to copy part of your PR description)

2022-01-19 13:40 UTC, leoetlino commented on src/components/AppMap.ts
> +  yTooltipOnEach(marker: any) {
enableYTooltip (or something else that makes it clearer what this function does)

2022-01-19 13:40 UTC, leoetlino commented on src/components/AppMap.ts
> +  yTooltipOffEach(marker: any) {
disableYTooltip? Funnily enough this reminds me of Nintendo's naming conventions for enabling and disabling things (they use on/off as a verb) :upside_down_face:

2022-01-19 13:40 UTC, leoetlino commented on src/components/AppMap.ts
> +    let func = (on) ? this.yTooltipOnEach : this.yTooltipOffEach;
```suggestion
    let func = on ? this.yTooltipOnEach : this.yTooltipOffEach;
```

2022-01-19 13:40 UTC, leoetlino commented on src/components/AppMap.ts
> +  yTooltipSwitch(on: boolean) {
toggleYTooltipOnAllMarkers (or something else that makes it clear that this function operates on every single map marker)

2022-01-19 13:40 UTC, leoetlino commented on src/components/AppMap.ts
> +  updateTooltip() {
updateTooltips (plural because this affects multiple markers)

2022-01-19 13:40 UTC, leoetlino commented on src/components/AppMap.ts
> +    if (this.staticTooltip) {
Could you explain the purpose of checking if staticTooltip is true? I don't see why it's useful when yTooltipSwitch already handles both false and true correctly

2022-01-19 13:40 UTC, leoetlino commented on src/components/AppMap.ts
> +    this.yTooltipSwitch(this.staticTooltip);
If you remove the check in updateTooltips(), this can become a call to updateTooltips().

2022-01-19 19:39 UTC, savage13 commented
Functions renamed for improved readability

The check in updateTooltips() was to avoid unnecessary unbinding and re-binding the tooltip (if the tooltip did not change).

I moved this check into the enable/disableYTooltip().  It now checks if the getTooltip().options.permanent flag and will only recreate the tooltip if it would cause a change in the tooltip.

2022-01-20 14:21 UTC, leoetlino approved these changes

2022-01-20 14:22 UTC, merged